import {
  AdminUser,
  Course,
  Chapter,
  VocabularyWord,
  LearningSessionConfig,
  LearningSequenceRule,
  Test,
  TestQuestion,
  ReviewSettingsConfig,
  Learner,
  LearnerHistoryItem,
  NotificationItem,
  PlatformAnalytics,
} from '@/types';

export const initialAdminUser: AdminUser = {
  id: 'admin_1',
  name: 'Marcus Weber',
  email: 'admin@telcmastery.com',
  role: 'SUPER_ADMIN',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  lastLogin: '2026-10-01T14:30:00Z',
};

export const initialCourses: Course[] = [
  {
    id: 'course_b1',
    title: 'B1 German Vocabulary',
    level: 'B1',
    description: 'Comprehensive TELC B1 exam vocabulary curriculum with 7 structured chapters covering work, accommodation, social life, and public administration.',
    translationLanguage: 'English',
    totalChapters: 7,
    totalVocabulary: 140,
    learnersCount: 1250,
    completionRate: 68,
    status: 'published',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-09-28T16:15:00Z',
  },
  {
    id: 'course_b2',
    title: 'B2 Professional German',
    level: 'B2',
    description: 'Advanced vocabulary for TELC B2 Beruf and academic communication, focusing on professional negotiations and technical argumentation.',
    translationLanguage: 'English',
    totalChapters: 6,
    totalVocabulary: 120,
    learnersCount: 680,
    completionRate: 44,
    status: 'published',
    createdAt: '2026-08-15T11:00:00Z',
    updatedAt: '2026-09-25T09:30:00Z',
  },
  {
    id: 'course_a2',
    title: 'A2 Essential German',
    level: 'A2',
    description: 'Core foundation vocabulary for everyday situations, directions, shopping, and doctor appointments.',
    translationLanguage: 'English',
    totalChapters: 5,
    totalVocabulary: 100,
    learnersCount: 520,
    completionRate: 74,
    status: 'draft',
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-29T12:00:00Z',
  },
];

export const initialChapters: Chapter[] = [
  {
    id: 'chap_b1_1',
    courseId: 'course_b1',
    courseTitle: 'B1 German Vocabulary',
    chapterNumber: 1,
    title: 'Wohnen & Umgebung (Living & Environment)',
    description: 'Vocabulary covering rental apartments, furniture, contracts, landlord communications, and household devices.',
    daysCount: 7,
    dailyWordTarget: 20,
    reviewEnabled: true,
    totalWords: 140,
    completedLearners: 840,
    status: 'published',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-09-20T14:00:00Z',
  },
  {
    id: 'chap_b1_2',
    courseId: 'course_b1',
    courseTitle: 'B1 German Vocabulary',
    chapterNumber: 2,
    title: 'Arbeitswelt & Beruf (Work & Career)',
    description: 'Job applications, employment contracts, office communication, and professional meetings in Germany.',
    daysCount: 7,
    dailyWordTarget: 20,
    reviewEnabled: true,
    totalWords: 140,
    completedLearners: 610,
    status: 'published',
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-09-22T14:00:00Z',
  },
  {
    id: 'chap_b1_3',
    courseId: 'course_b1',
    courseTitle: 'B1 German Vocabulary',
    chapterNumber: 3,
    title: 'Gesundheit & Medizin (Health & Medicine)',
    description: 'Consultations, pharmacy terms, symptoms, healthcare insurance, and emergency vocabulary.',
    daysCount: 7,
    dailyWordTarget: 20,
    reviewEnabled: true,
    totalWords: 140,
    completedLearners: 420,
    status: 'published',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-09-25T14:00:00Z',
  },
  {
    id: 'chap_b1_4',
    courseId: 'course_b1',
    courseTitle: 'B1 German Vocabulary',
    chapterNumber: 4,
    title: 'Behörden & Finanzen (Authorities & Finance)',
    description: 'Registration office (Bürgeramt), tax declarations, banking, visa renewals, and legal formalities.',
    daysCount: 7,
    dailyWordTarget: 20,
    reviewEnabled: true,
    totalWords: 140,
    completedLearners: 290,
    status: 'draft',
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-09-26T14:00:00Z',
  },
];

export const initialVocabulary: VocabularyWord[] = [
  {
    id: 'v_1',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    chapterTitle: 'Wohnen & Umgebung',
    german: 'der Tisch',
    english: 'Table',
    article: 'der',
    partOfSpeech: 'Noun',
    pronunciation: '/tɪʃ/',
    audioUrl: '/audio/tisch.mp3',
    difficulty: 'Easy',
    tags: ['Furniture', 'Living', 'Essentials'],
    exampleGerman: 'Wir setzen uns alle an den großen Tisch im Esszimmer.',
    exampleEnglish: 'We all sit down at the large table in the dining room.',
    timesLearned: 1200,
    timesTested: 1050,
    correctAnswers: 980,
    incorrectAnswers: 70,
    accuracy: 93.3,
    reviewCount: 310,
    status: 'active',
    createdAt: '2026-08-11T12:00:00Z',
  },
  {
    id: 'v_2',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    chapterTitle: 'Wohnen & Umgebung',
    german: 'die Wohnung',
    english: 'Apartment / Flat',
    article: 'die',
    partOfSpeech: 'Noun',
    pronunciation: '/ˈvoːnʊŋ/',
    audioUrl: '/audio/wohnung.mp3',
    difficulty: 'Easy',
    tags: ['Living', 'Real Estate'],
    exampleGerman: 'Die Wohnung hat drei Zimmer und einen schönen Balkon.',
    exampleEnglish: 'The apartment has three rooms and a nice balcony.',
    timesLearned: 1180,
    timesTested: 1040,
    correctAnswers: 975,
    incorrectAnswers: 65,
    accuracy: 93.8,
    reviewCount: 290,
    status: 'active',
    createdAt: '2026-08-11T12:05:00Z',
  },
  {
    id: 'v_3',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    chapterTitle: 'Wohnen & Umgebung',
    german: 'das Fenster',
    english: 'Window',
    article: 'das',
    partOfSpeech: 'Noun',
    pronunciation: '/ˈfɛnstɐ/',
    audioUrl: '/audio/fenster.mp3',
    difficulty: 'Easy',
    tags: ['House', 'Architecture'],
    exampleGerman: 'Bitte öffnen Sie das Fenster, um frische Luft hereinzulassen.',
    exampleEnglish: 'Please open the window to let in fresh air.',
    timesLearned: 1150,
    timesTested: 980,
    correctAnswers: 890,
    incorrectAnswers: 90,
    accuracy: 90.8,
    reviewCount: 260,
    status: 'active',
    createdAt: '2026-08-11T12:10:00Z',
  },
  {
    id: 'v_4',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    chapterTitle: 'Wohnen & Umgebung',
    german: 'der Mietvertrag',
    english: 'Rental agreement / Lease',
    article: 'der',
    partOfSpeech: 'Noun',
    pronunciation: '/ˈmiːtfɛɐ̯ˌtʁaːk/',
    audioUrl: '/audio/mietvertrag.mp3',
    difficulty: 'Hard',
    tags: ['Contracts', 'Legal', 'Living'],
    exampleGerman: 'Vor dem Einzug müssen beide Parteien den Mietvertrag unterschreiben.',
    exampleEnglish: 'Before moving in, both parties must sign the rental agreement.',
    timesLearned: 980,
    timesTested: 890,
    correctAnswers: 620,
    incorrectAnswers: 270,
    accuracy: 69.7,
    reviewCount: 540,
    status: 'active',
    createdAt: '2026-08-11T12:15:00Z',
  },
  {
    id: 'v_5',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    chapterTitle: 'Wohnen & Umgebung',
    german: 'die Nebenkosten',
    english: 'Additional utility costs',
    article: 'die',
    partOfSpeech: 'Noun',
    pronunciation: '/ˈneːbn̩ˌkɔstn̩/',
    audioUrl: '/audio/nebenkosten.mp3',
    difficulty: 'Medium',
    tags: ['Finance', 'Housing'],
    exampleGerman: 'Die monatliche Warmmiete beinhaltet bereits alle Nebenkosten.',
    exampleEnglish: 'The monthly warm rent already includes all utility costs.',
    timesLearned: 940,
    timesTested: 820,
    correctAnswers: 640,
    incorrectAnswers: 180,
    accuracy: 78.0,
    reviewCount: 410,
    status: 'active',
    createdAt: '2026-08-11T12:20:00Z',
  },
  {
    id: 'v_6',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    chapterTitle: 'Wohnen & Umgebung',
    german: 'renovieren',
    english: 'to renovate / redecorate',
    article: 'none',
    partOfSpeech: 'Verb',
    pronunciation: '/ʁenoˈviːʁən/',
    audioUrl: '/audio/renovieren.mp3',
    difficulty: 'Medium',
    tags: ['Home Improvement', 'Verbs'],
    exampleGerman: 'Wir möchten die alte Küche im kommenden Frühjahr renovieren.',
    exampleEnglish: 'We would like to renovate the old kitchen next spring.',
    timesLearned: 890,
    timesTested: 750,
    correctAnswers: 630,
    incorrectAnswers: 120,
    accuracy: 84.0,
    reviewCount: 300,
    status: 'active',
    createdAt: '2026-08-11T12:25:00Z',
  },
  {
    id: 'v_7',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    chapterTitle: 'Wohnen & Umgebung',
    german: 'gemütlich',
    english: 'cozy / comfortable',
    article: 'none',
    partOfSpeech: 'Adjective',
    pronunciation: '/ɡəˈmyːtlɪç/',
    audioUrl: '/audio/gemuetlich.mp3',
    difficulty: 'Easy',
    tags: ['Adjectives', 'Feelings'],
    exampleGerman: 'Das Wohnzimmer ist durch die warmen Holzmöbel sehr gemütlich.',
    exampleEnglish: 'The living room is very cozy due to the warm wooden furniture.',
    timesLearned: 1120,
    timesTested: 990,
    correctAnswers: 920,
    incorrectAnswers: 70,
    accuracy: 92.9,
    reviewCount: 220,
    status: 'active',
    createdAt: '2026-08-11T12:30:00Z',
  },
  {
    id: 'v_8',
    courseId: 'course_b1',
    chapterId: 'chap_b1_2',
    chapterTitle: 'Arbeitswelt & Beruf',
    german: 'die Bewerbung',
    english: 'Job application',
    article: 'die',
    partOfSpeech: 'Noun',
    pronunciation: '/bəˈvɛʁbʊŋ/',
    audioUrl: '/audio/bewerbung.mp3',
    difficulty: 'Medium',
    tags: ['Career', 'Application'],
    exampleGerman: 'Ich habe meine Bewerbung zusammen mit dem Lebenslauf eingereicht.',
    exampleEnglish: 'I submitted my application together with my curriculum vitae.',
    timesLearned: 870,
    timesTested: 760,
    correctAnswers: 670,
    incorrectAnswers: 90,
    accuracy: 88.2,
    reviewCount: 280,
    status: 'active',
    createdAt: '2026-08-13T10:00:00Z',
  },
  {
    id: 'v_9',
    courseId: 'course_b1',
    chapterId: 'chap_b1_2',
    chapterTitle: 'Arbeitswelt & Beruf',
    german: 'das Vorstellungsgespräch',
    english: 'Job interview',
    article: 'das',
    partOfSpeech: 'Noun',
    pronunciation: '/ˈfoːɐ̯ʃtɛlʊŋsɡəˌʃpʁɛːç/',
    audioUrl: '/audio/vorstellungsgespraech.mp3',
    difficulty: 'Hard',
    tags: ['Career', 'Interview', 'Compound Word'],
    exampleGerman: 'Das Vorstellungsgespräch verlief positiv und dauerte fast eine Stunde.',
    exampleEnglish: 'The job interview went well and lasted almost an hour.',
    timesLearned: 820,
    timesTested: 710,
    correctAnswers: 490,
    incorrectAnswers: 220,
    accuracy: 69.0,
    reviewCount: 460,
    status: 'active',
    createdAt: '2026-08-13T10:10:00Z',
  },
  {
    id: 'v_10',
    courseId: 'course_b1',
    chapterId: 'chap_b1_2',
    chapterTitle: 'Arbeitswelt & Beruf',
    german: 'verhandeln',
    english: 'to negotiate',
    article: 'none',
    partOfSpeech: 'Verb',
    pronunciation: '/fɛɐ̯ˈhandl̩n/',
    audioUrl: '/audio/verhandeln.mp3',
    difficulty: 'Medium',
    tags: ['Business', 'Communication'],
    exampleGerman: 'Die Gewerkschaft verhandelt mit den Arbeitgebern über höhere Löhne.',
    exampleEnglish: 'The union is negotiating with employers for higher wages.',
    timesLearned: 790,
    timesTested: 680,
    correctAnswers: 550,
    incorrectAnswers: 130,
    accuracy: 80.9,
    reviewCount: 310,
    status: 'active',
    createdAt: '2026-08-13T10:15:00Z',
  },
];

export const initialLearningSessions: LearningSessionConfig[] = [
  {
    id: 'ls_1',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    dayNumber: 1,
    newWordsCount: 20,
    previousWordsCount: 0,
    totalWordsCount: 20,
    durationMinutes: 3,
    cumulativeTestEnabled: true,
    reviewPreviousEnabled: false,
    status: 'active',
  },
  {
    id: 'ls_2',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    dayNumber: 2,
    newWordsCount: 20,
    previousWordsCount: 10,
    totalWordsCount: 30,
    durationMinutes: 4,
    cumulativeTestEnabled: true,
    reviewPreviousEnabled: true,
    status: 'active',
  },
  {
    id: 'ls_3',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    dayNumber: 3,
    newWordsCount: 20,
    previousWordsCount: 10,
    totalWordsCount: 30,
    durationMinutes: 4,
    cumulativeTestEnabled: true,
    reviewPreviousEnabled: true,
    status: 'active',
  },
  {
    id: 'ls_4',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    dayNumber: 4,
    newWordsCount: 20,
    previousWordsCount: 10,
    totalWordsCount: 30,
    durationMinutes: 4,
    cumulativeTestEnabled: true,
    reviewPreviousEnabled: true,
    status: 'active',
  },
  {
    id: 'ls_5',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    dayNumber: 5,
    newWordsCount: 20,
    previousWordsCount: 10,
    totalWordsCount: 30,
    durationMinutes: 4,
    cumulativeTestEnabled: true,
    reviewPreviousEnabled: true,
    status: 'active',
  },
  {
    id: 'ls_6',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    dayNumber: 6,
    newWordsCount: 20,
    previousWordsCount: 10,
    totalWordsCount: 30,
    durationMinutes: 4,
    cumulativeTestEnabled: true,
    reviewPreviousEnabled: true,
    status: 'active',
  },
  {
    id: 'ls_7',
    courseId: 'course_b1',
    chapterId: 'chap_b1_1',
    dayNumber: 7,
    newWordsCount: 20,
    previousWordsCount: 10,
    totalWordsCount: 30,
    durationMinutes: 5,
    cumulativeTestEnabled: true,
    reviewPreviousEnabled: true,
    status: 'active',
  },
];

export const initialLearningSequence: LearningSequenceRule = {
  wordsPerBatch: 4,
  dailyTarget: 20,
  learningTimeMinutes: 3,
  randomizeQuestions: true,
  cumulativeTestEnabled: true,
  repeatUntilTarget: true,
};

export const initialReviewSettings: ReviewSettingsConfig = {
  reviewPreviousWords: true,
  selectionStrategy: 'Automatic',
  maxPreviousWords: 10,
  reviewFrequency: 'Daily',
  randomOrder: true,
  chapterReview: true,
  overallReview: true,
  newWordsPerDay: 20,
};

export const initialTests: Test[] = [
  {
    id: 'test_1',
    title: 'Chapter 1 Vocabulary Test',
    type: 'Translation',
    courseId: 'course_b1',
    courseTitle: 'B1 German Vocabulary',
    chapterId: 'chap_b1_1',
    chapterTitle: 'Wohnen & Umgebung',
    questionSelection: 'Automatic',
    randomize: true,
    questionsCount: 20,
    attemptsCount: 1140,
    averageScore: 88.4,
    status: 'active',
    createdAt: '2026-08-14T09:00:00Z',
  },
  {
    id: 'test_2',
    title: 'Days 1-4 Cumulative Test',
    type: 'Cumulative',
    courseId: 'course_b1',
    courseTitle: 'B1 German Vocabulary',
    chapterId: 'chap_b1_1',
    chapterTitle: 'Wohnen & Umgebung',
    questionSelection: 'Automatic',
    randomize: true,
    questionsCount: 30,
    attemptsCount: 780,
    averageScore: 82.1,
    status: 'active',
    createdAt: '2026-08-16T11:30:00Z',
  },
  {
    id: 'test_3',
    title: 'Chapter 1 Comprehensive Review Exam',
    type: 'ChapterReview',
    courseId: 'course_b1',
    courseTitle: 'B1 German Vocabulary',
    chapterId: 'chap_b1_1',
    chapterTitle: 'Wohnen & Umgebung',
    questionSelection: 'Manual',
    randomize: true,
    questionsCount: 50,
    attemptsCount: 650,
    averageScore: 85.7,
    status: 'active',
    createdAt: '2026-08-18T15:00:00Z',
  },
];

export const initialTestQuestions: TestQuestion[] = [
  {
    id: 'tq_1',
    testId: 'test_1',
    englishPrompt: 'Table',
    correctGerman: 'der Tisch',
    questionType: 'Translation',
    acceptedAnswers: ['der Tisch', 'Tisch'],
    difficulty: 'Easy',
    orderIndex: 1,
  },
  {
    id: 'tq_2',
    testId: 'test_1',
    englishPrompt: 'Apartment / Flat',
    correctGerman: 'die Wohnung',
    questionType: 'Translation',
    acceptedAnswers: ['die Wohnung', 'Wohnung'],
    difficulty: 'Easy',
    orderIndex: 2,
  },
  {
    id: 'tq_3',
    testId: 'test_1',
    englishPrompt: 'Rental agreement / Lease',
    correctGerman: 'der Mietvertrag',
    questionType: 'Translation',
    acceptedAnswers: ['der Mietvertrag', 'Mietvertrag'],
    difficulty: 'Hard',
    orderIndex: 3,
  },
  {
    id: 'tq_4',
    testId: 'test_1',
    englishPrompt: 'Window',
    correctGerman: 'das Fenster',
    questionType: 'Translation',
    acceptedAnswers: ['das Fenster', 'Fenster'],
    difficulty: 'Easy',
    orderIndex: 4,
  },
];

export const initialLearners: Learner[] = [
  {
    id: 'usr_1',
    name: 'Sophie Martinez',
    email: 'sophie.martinez@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    courseId: 'course_b1',
    courseName: 'B1 German Vocabulary',
    chapterId: 'chap_b1_3',
    chapterName: 'Chapter 3: Gesundheit & Medizin',
    progressPercentage: 42,
    wordsLearned: 420,
    wordsReviewed: 180,
    testsCompleted: 35,
    averageScore: 87,
    lastActive: '2026-10-01T15:20:00Z',
    status: 'active',
    joinedDate: '2026-08-14T09:30:00Z',
  },
  {
    id: 'usr_2',
    name: 'Alexander Chen',
    email: 'alex.chen@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    courseId: 'course_b1',
    courseName: 'B1 German Vocabulary',
    chapterId: 'chap_b1_2',
    chapterName: 'Chapter 2: Arbeitswelt & Beruf',
    progressPercentage: 28,
    wordsLearned: 280,
    wordsReviewed: 110,
    testsCompleted: 22,
    averageScore: 92,
    lastActive: '2026-10-01T14:45:00Z',
    status: 'active',
    joinedDate: '2026-08-20T11:15:00Z',
  },
  {
    id: 'usr_3',
    name: 'Elena Rostova',
    email: 'elena.rostova@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    courseId: 'course_b1',
    courseName: 'B1 German Vocabulary',
    chapterId: 'chap_b1_4',
    chapterName: 'Chapter 4: Behörden & Finanzen',
    progressPercentage: 58,
    wordsLearned: 560,
    wordsReviewed: 290,
    testsCompleted: 44,
    averageScore: 89,
    lastActive: '2026-10-01T11:10:00Z',
    status: 'active',
    joinedDate: '2026-08-12T08:00:00Z',
  },
  {
    id: 'usr_4',
    name: 'Lucas Silva',
    email: 'lucas.silva@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    courseId: 'course_b2',
    courseName: 'B2 Professional German',
    chapterId: 'chap_b2_1',
    chapterName: 'Chapter 1: Verhandlungen',
    progressPercentage: 15,
    wordsLearned: 140,
    wordsReviewed: 45,
    testsCompleted: 11,
    averageScore: 78,
    lastActive: '2026-09-30T16:00:00Z',
    status: 'active',
    joinedDate: '2026-09-02T13:40:00Z',
  },
  {
    id: 'usr_5',
    name: 'Amara Diallo',
    email: 'amara.diallo@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    courseId: 'course_b1',
    courseName: 'B1 German Vocabulary',
    chapterId: 'chap_b1_1',
    chapterName: 'Chapter 1: Wohnen & Umgebung',
    progressPercentage: 8,
    wordsLearned: 60,
    wordsReviewed: 15,
    testsCompleted: 5,
    averageScore: 74,
    lastActive: '2026-09-24T10:10:00Z',
    status: 'inactive',
    joinedDate: '2026-09-18T10:00:00Z',
  },
  {
    id: 'usr_6',
    name: 'David Müller',
    email: 'd.mueller@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80',
    courseId: 'course_b1',
    courseName: 'B1 German Vocabulary',
    chapterId: 'chap_b1_2',
    chapterName: 'Chapter 2: Arbeitswelt & Beruf',
    progressPercentage: 35,
    wordsLearned: 340,
    wordsReviewed: 160,
    testsCompleted: 28,
    averageScore: 84,
    lastActive: '2026-10-01T09:25:00Z',
    status: 'suspended',
    joinedDate: '2026-08-25T14:20:00Z',
  },
];

export const initialLearnerHistory: LearnerHistoryItem[] = [
  {
    id: 'h_1',
    dayNumber: 1,
    date: '2026-09-25',
    newWordsLearned: 20,
    wordsReviewed: 0,
    testScore: 95,
    timeSpentMinutes: 8,
    status: 'completed',
  },
  {
    id: 'h_2',
    dayNumber: 2,
    date: '2026-09-26',
    newWordsLearned: 20,
    wordsReviewed: 10,
    testScore: 90,
    timeSpentMinutes: 11,
    status: 'completed',
  },
  {
    id: 'h_3',
    dayNumber: 3,
    date: '2026-09-27',
    newWordsLearned: 20,
    wordsReviewed: 10,
    testScore: 85,
    timeSpentMinutes: 12,
    status: 'completed',
  },
  {
    id: 'h_4',
    dayNumber: 4,
    date: '2026-09-28',
    newWordsLearned: 20,
    wordsReviewed: 10,
    testScore: 88,
    timeSpentMinutes: 10,
    status: 'completed',
  },
  {
    id: 'h_5',
    dayNumber: 5,
    date: '2026-09-29',
    newWordsLearned: 20,
    wordsReviewed: 10,
    testScore: 92,
    timeSpentMinutes: 11,
    status: 'completed',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Daily Streak Reminder 🔥',
    message: 'Keep your TELC preparation momentum! Complete your 20 vocabulary words for today.',
    audience: 'All Users',
    type: 'Push',
    status: 'Sent',
    sentAt: '2026-10-01T08:00:00Z',
    targetCount: 2450,
    readCount: 1680,
  },
  {
    id: 'notif_2',
    title: 'New B1 Practice Examination Available',
    message: 'Check out the Chapter 3 Medical German vocabulary test now live in your curriculum.',
    audience: 'B1 Course',
    type: 'In-App',
    status: 'Sent',
    sentAt: '2026-09-29T14:30:00Z',
    targetCount: 1250,
    readCount: 940,
  },
  {
    id: 'notif_3',
    title: 'We miss you! 5-minute review session',
    message: 'Come back and review 10 previous words to keep them fresh in your active memory.',
    audience: 'Inactive Users',
    type: 'Push',
    status: 'Scheduled',
    scheduledAt: '2026-10-02T10:00:00Z',
    targetCount: 380,
    readCount: 0,
  },
];

export const initialAnalytics: PlatformAnalytics = {
  totalLearners: 2450,
  activeLearners: 1840,
  totalCourses: 3,
  totalChapters: 18,
  totalVocabulary: 360,
  completedSessions: 8940,
  learnersGrowth: 12.5,
  sessionsToday: 412,
  avgCompletionRate: 68.4,
  dailyActiveLearners: 890,
  weeklyActiveLearners: 1840,
  wordsLearnedTotal: 42800,
  wordsReviewedTotal: 18400,
  testsCompletedTotal: 6250,
  avgTestScore: 86.8,
};

export const activityTrend7Days = [
  { day: 'Mon', sessions: 320, words: 1420, tests: 210 },
  { day: 'Tue', sessions: 380, words: 1680, tests: 260 },
  { day: 'Wed', sessions: 340, words: 1540, tests: 230 },
  { day: 'Thu', sessions: 410, words: 1890, tests: 290 },
  { day: 'Fri', sessions: 390, words: 1720, tests: 280 },
  { day: 'Sat', sessions: 460, words: 2100, tests: 340 },
  { day: 'Sun', sessions: 412, words: 1950, tests: 310 },
];
